[package]
name = "crabvm"
description = "Bytecode VM for Crabby"
authors = ["Kazooki123 <mgamerdinge146@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "crabvm"
path = "src/main.rs"

[dependencies]
crabc = { path = "../compiler", version = "0.1.0" }
